package com.example.firstnetworkapi.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class Schools(
    @Json(name = "academicopportunities1")
    val academicopportunities1: String? = null,
    @Json(name = "academicopportunities2")
    val academicopportunities2: String? = null,
    @Json(name = "academicopportunities3")
    val academicopportunities3: String? = null,
    @Json(name = "academicopportunities4")
    val academicopportunities4: String? = null,
    @Json(name = "academicopportunities5")
    val academicopportunities5: String? = null,
    @Json(name = "addtl_info1")
    val addtlInfo1: String? = null,
    @Json(name = "admissionspriority11")
    val admissionspriority11: String? = null,
    @Json(name = "admissionspriority110")
    val admissionspriority110: String? = null,
    @Json(name = "admissionspriority12")
    val admissionspriority12: String? = null,
    @Json(name = "admissionspriority13")
    val admissionspriority13: String? = null,
    @Json(name = "admissionspriority14")
    val admissionspriority14: String? = null,
    @Json(name = "admissionspriority15")
    val admissionspriority15: String? = null,
    @Json(name = "admissionspriority16")
    val admissionspriority16: String? = null,
    @Json(name = "admissionspriority17")
    val admissionspriority17: String? = null,
    @Json(name = "admissionspriority18")
    val admissionspriority18: String? = null,
    @Json(name = "admissionspriority19")
    val admissionspriority19: String? = null,
    @Json(name = "admissionspriority21")
    val admissionspriority21: String? = null,
    @Json(name = "admissionspriority22")
    val admissionspriority22: String? = null,
    @Json(name = "admissionspriority23")
    val admissionspriority23: String? = null,
    @Json(name = "admissionspriority24")
    val admissionspriority24: String? = null,
    @Json(name = "admissionspriority25")
    val admissionspriority25: String? = null,
    @Json(name = "admissionspriority26")
    val admissionspriority26: String? = null,
    @Json(name = "admissionspriority27")
    val admissionspriority27: String? = null,
    @Json(name = "admissionspriority28")
    val admissionspriority28: String? = null,
    @Json(name = "admissionspriority29")
    val admissionspriority29: String? = null,
    @Json(name = "admissionspriority31")
    val admissionspriority31: String? = null,
    @Json(name = "admissionspriority32")
    val admissionspriority32: String? = null,
    @Json(name = "admissionspriority33")
    val admissionspriority33: String? = null,
    @Json(name = "admissionspriority34")
    val admissionspriority34: String? = null,
    @Json(name = "admissionspriority35")
    val admissionspriority35: String? = null,
    @Json(name = "admissionspriority36")
    val admissionspriority36: String? = null,
    @Json(name = "admissionspriority37")
    val admissionspriority37: String? = null,
    @Json(name = "admissionspriority41")
    val admissionspriority41: String? = null,
    @Json(name = "admissionspriority42")
    val admissionspriority42: String? = null,
    @Json(name = "admissionspriority43")
    val admissionspriority43: String? = null,
    @Json(name = "admissionspriority44")
    val admissionspriority44: String? = null,
    @Json(name = "admissionspriority46")
    val admissionspriority46: String? = null,
    @Json(name = "admissionspriority51")
    val admissionspriority51: String? = null,
    @Json(name = "admissionspriority52")
    val admissionspriority52: String? = null,
    @Json(name = "admissionspriority53")
    val admissionspriority53: String? = null,
    @Json(name = "admissionspriority54")
    val admissionspriority54: String? = null,
    @Json(name = "admissionspriority56")
    val admissionspriority56: String? = null,
    @Json(name = "admissionspriority61")
    val admissionspriority61: String? = null,
    @Json(name = "admissionspriority62")
    val admissionspriority62: String? = null,
    @Json(name = "admissionspriority63")
    val admissionspriority63: String? = null,
    @Json(name = "admissionspriority64")
    val admissionspriority64: String? = null,
    @Json(name = "admissionspriority71")
    val admissionspriority71: String? = null,
    @Json(name = "admissionspriority74")
    val admissionspriority74: String? = null,
    @Json(name = "advancedplacement_courses")
    val advancedplacementCourses: String? = null,
    @Json(name = "applicants1specialized")
    val applicants1specialized: String? = null,
    @Json(name = "applicants2specialized")
    val applicants2specialized: String? = null,
    @Json(name = "applicants3specialized")
    val applicants3specialized: String? = null,
    @Json(name = "applicants4specialized")
    val applicants4specialized: String? = null,
    @Json(name = "applicants5specialized")
    val applicants5specialized: String? = null,
    @Json(name = "applicants6specialized")
    val applicants6specialized: String? = null,
    @Json(name = "appperseat1specialized")
    val appperseat1specialized: String? = null,
    @Json(name = "appperseat2specialized")
    val appperseat2specialized: String? = null,
    @Json(name = "appperseat3specialized")
    val appperseat3specialized: String? = null,
    @Json(name = "appperseat4specialized")
    val appperseat4specialized: String? = null,
    @Json(name = "appperseat5specialized")
    val appperseat5specialized: String? = null,
    @Json(name = "appperseat6specialized")
    val appperseat6specialized: String? = null,
    @Json(name = "attendance_rate")
    val attendanceRate: String? = null,
    @Json(name = "auditioninformation1")
    val auditioninformation1: String? = null,
    @Json(name = "auditioninformation2")
    val auditioninformation2: String? = null,
    @Json(name = "auditioninformation3")
    val auditioninformation3: String? = null,
    @Json(name = "auditioninformation4")
    val auditioninformation4: String? = null,
    @Json(name = "auditioninformation5")
    val auditioninformation5: String? = null,
    @Json(name = "auditioninformation6")
    val auditioninformation6: String? = null,
    @Json(name = "auditioninformation7")
    val auditioninformation7: String? = null,
    @Json(name = "bbl")
    val bbl: String? = null,
    @Json(name = "bin")
    val bin: String? = null,
    @Json(name = "boro")
    val boro: String? = null,
    @Json(name = "borough")
    val borough: String? = null,
    @Json(name = "boys")
    val boys: String? = null,
    @Json(name = "building_code")
    val buildingCode: String? = null,
    @Json(name = "bus")
    val bus: String? = null,
    @Json(name = "campus_name")
    val campusName: String? = null,
    @Json(name = "census_tract")
    val censusTract: String? = null,
    @Json(name = "city")
    val city: String? = null,
    @Json(name = "code1")
    val code1: String? = null,
    @Json(name = "code10")
    val code10: String? = null,
    @Json(name = "code2")
    val code2: String? = null,
    @Json(name = "code3")
    val code3: String? = null,
    @Json(name = "code4")
    val code4: String? = null,
    @Json(name = "code5")
    val code5: String? = null,
    @Json(name = "code6")
    val code6: String? = null,
    @Json(name = "code7")
    val code7: String? = null,
    @Json(name = "code8")
    val code8: String? = null,
    @Json(name = "code9")
    val code9: String? = null,
    @Json(name = "college_career_rate")
    val collegeCareerRate: String? = null,
    @Json(name = "common_audition1")
    val commonAudition1: String? = null,
    @Json(name = "common_audition2")
    val commonAudition2: String? = null,
    @Json(name = "common_audition3")
    val commonAudition3: String? = null,
    @Json(name = "common_audition4")
    val commonAudition4: String? = null,
    @Json(name = "common_audition5")
    val commonAudition5: String? = null,
    @Json(name = "common_audition6")
    val commonAudition6: String? = null,
    @Json(name = "common_audition7")
    val commonAudition7: String? = null,
    @Json(name = "community_board")
    val communityBoard: String? = null,
    @Json(name = "council_district")
    val councilDistrict: String? = null,
    @Json(name = "dbn")
    val dbn: String? = null,
    @Json(name = "diplomaendorsements")
    val diplomaendorsements: String? = null,
    @Json(name = "directions1")
    val directions1: String? = null,
    @Json(name = "directions2")
    val directions2: String? = null,
    @Json(name = "directions3")
    val directions3: String? = null,
    @Json(name = "directions4")
    val directions4: String? = null,
    @Json(name = "directions5")
    val directions5: String? = null,
    @Json(name = "directions6")
    val directions6: String? = null,
    @Json(name = "directions7")
    val directions7: String? = null,
    @Json(name = "earlycollege")
    val earlycollege: String? = null,
    @Json(name = "eligibility1")
    val eligibility1: String? = null,
    @Json(name = "eligibility2")
    val eligibility2: String? = null,
    @Json(name = "eligibility3")
    val eligibility3: String? = null,
    @Json(name = "eligibility4")
    val eligibility4: String? = null,
    @Json(name = "eligibility5")
    val eligibility5: String? = null,
    @Json(name = "eligibility6")
    val eligibility6: String? = null,
    @Json(name = "eligibility7")
    val eligibility7: String? = null,
    @Json(name = "ell_programs")
    val ellPrograms: String? = null,
    @Json(name = "end_time")
    val endTime: String? = null,
    @Json(name = "extracurricular_activities")
    val extracurricularActivities: String? = null,
    @Json(name = "fax_number")
    val faxNumber: String? = null,
    @Json(name = "finalgrades")
    val finalgrades: String? = null,
    @Json(name = "geoeligibility")
    val geoeligibility: String? = null,
    @Json(name = "girls")
    val girls: String? = null,
    @Json(name = "grade9geapplicants1")
    val grade9geapplicants1: String? = null,
    @Json(name = "grade9geapplicants10")
    val grade9geapplicants10: String? = null,
    @Json(name = "grade9geapplicants2")
    val grade9geapplicants2: String? = null,
    @Json(name = "grade9geapplicants3")
    val grade9geapplicants3: String? = null,
    @Json(name = "grade9geapplicants4")
    val grade9geapplicants4: String? = null,
    @Json(name = "grade9geapplicants5")
    val grade9geapplicants5: String? = null,
    @Json(name = "grade9geapplicants6")
    val grade9geapplicants6: String? = null,
    @Json(name = "grade9geapplicants7")
    val grade9geapplicants7: String? = null,
    @Json(name = "grade9geapplicants8")
    val grade9geapplicants8: String? = null,
    @Json(name = "grade9geapplicants9")
    val grade9geapplicants9: String? = null,
    @Json(name = "grade9geapplicantsperseat1")
    val grade9geapplicantsperseat1: String? = null,
    @Json(name = "grade9geapplicantsperseat10")
    val grade9geapplicantsperseat10: String? = null,
    @Json(name = "grade9geapplicantsperseat2")
    val grade9geapplicantsperseat2: String? = null,
    @Json(name = "grade9geapplicantsperseat3")
    val grade9geapplicantsperseat3: String? = null,
    @Json(name = "grade9geapplicantsperseat4")
    val grade9geapplicantsperseat4: String? = null,
    @Json(name = "grade9geapplicantsperseat5")
    val grade9geapplicantsperseat5: String? = null,
    @Json(name = "grade9geapplicantsperseat6")
    val grade9geapplicantsperseat6: String? = null,
    @Json(name = "grade9geapplicantsperseat7")
    val grade9geapplicantsperseat7: String? = null,
    @Json(name = "grade9geapplicantsperseat8")
    val grade9geapplicantsperseat8: String? = null,
    @Json(name = "grade9geapplicantsperseat9")
    val grade9geapplicantsperseat9: String? = null,
    @Json(name = "grade9gefilledflag1")
    val grade9gefilledflag1: String? = null,
    @Json(name = "grade9gefilledflag10")
    val grade9gefilledflag10: String? = null,
    @Json(name = "grade9gefilledflag2")
    val grade9gefilledflag2: String? = null,
    @Json(name = "grade9gefilledflag3")
    val grade9gefilledflag3: String? = null,
    @Json(name = "grade9gefilledflag4")
    val grade9gefilledflag4: String? = null,
    @Json(name = "grade9gefilledflag5")
    val grade9gefilledflag5: String? = null,
    @Json(name = "grade9gefilledflag6")
    val grade9gefilledflag6: String? = null,
    @Json(name = "grade9gefilledflag7")
    val grade9gefilledflag7: String? = null,
    @Json(name = "grade9gefilledflag8")
    val grade9gefilledflag8: String? = null,
    @Json(name = "grade9gefilledflag9")
    val grade9gefilledflag9: String? = null,
    @Json(name = "grade9swdapplicants1")
    val grade9swdapplicants1: String? = null,
    @Json(name = "grade9swdapplicants10")
    val grade9swdapplicants10: String? = null,
    @Json(name = "grade9swdapplicants2")
    val grade9swdapplicants2: String? = null,
    @Json(name = "grade9swdapplicants3")
    val grade9swdapplicants3: String? = null,
    @Json(name = "grade9swdapplicants4")
    val grade9swdapplicants4: String? = null,
    @Json(name = "grade9swdapplicants5")
    val grade9swdapplicants5: String? = null,
    @Json(name = "grade9swdapplicants6")
    val grade9swdapplicants6: String? = null,
    @Json(name = "grade9swdapplicants7")
    val grade9swdapplicants7: String? = null,
    @Json(name = "grade9swdapplicants8")
    val grade9swdapplicants8: String? = null,
    @Json(name = "grade9swdapplicants9")
    val grade9swdapplicants9: String? = null,
    @Json(name = "grade9swdapplicantsperseat1")
    val grade9swdapplicantsperseat1: String? = null,
    @Json(name = "grade9swdapplicantsperseat10")
    val grade9swdapplicantsperseat10: String? = null,
    @Json(name = "grade9swdapplicantsperseat2")
    val grade9swdapplicantsperseat2: String? = null,
    @Json(name = "grade9swdapplicantsperseat3")
    val grade9swdapplicantsperseat3: String? = null,
    @Json(name = "grade9swdapplicantsperseat4")
    val grade9swdapplicantsperseat4: String? = null,
    @Json(name = "grade9swdapplicantsperseat5")
    val grade9swdapplicantsperseat5: String? = null,
    @Json(name = "grade9swdapplicantsperseat6")
    val grade9swdapplicantsperseat6: String? = null,
    @Json(name = "grade9swdapplicantsperseat7")
    val grade9swdapplicantsperseat7: String? = null,
    @Json(name = "grade9swdapplicantsperseat8")
    val grade9swdapplicantsperseat8: String? = null,
    @Json(name = "grade9swdapplicantsperseat9")
    val grade9swdapplicantsperseat9: String? = null,
    @Json(name = "grade9swdfilledflag1")
    val grade9swdfilledflag1: String? = null,
    @Json(name = "grade9swdfilledflag10")
    val grade9swdfilledflag10: String? = null,
    @Json(name = "grade9swdfilledflag2")
    val grade9swdfilledflag2: String? = null,
    @Json(name = "grade9swdfilledflag3")
    val grade9swdfilledflag3: String? = null,
    @Json(name = "grade9swdfilledflag4")
    val grade9swdfilledflag4: String? = null,
    @Json(name = "grade9swdfilledflag5")
    val grade9swdfilledflag5: String? = null,
    @Json(name = "grade9swdfilledflag6")
    val grade9swdfilledflag6: String? = null,
    @Json(name = "grade9swdfilledflag7")
    val grade9swdfilledflag7: String? = null,
    @Json(name = "grade9swdfilledflag8")
    val grade9swdfilledflag8: String? = null,
    @Json(name = "grade9swdfilledflag9")
    val grade9swdfilledflag9: String? = null,
    @Json(name = "grades2018")
    val grades2018: String? = null,
    @Json(name = "graduation_rate")
    val graduationRate: String? = null,
    @Json(name = "interest1")
    val interest1: String? = null,
    @Json(name = "interest10")
    val interest10: String? = null,
    @Json(name = "interest2")
    val interest2: String? = null,
    @Json(name = "interest3")
    val interest3: String? = null,
    @Json(name = "interest4")
    val interest4: String? = null,
    @Json(name = "interest5")
    val interest5: String? = null,
    @Json(name = "interest6")
    val interest6: String? = null,
    @Json(name = "interest7")
    val interest7: String? = null,
    @Json(name = "interest8")
    val interest8: String? = null,
    @Json(name = "interest9")
    val interest9: String? = null,
    @Json(name = "international")
    val international: String? = null,
    @Json(name = "language_classes")
    val languageClasses: String? = null,
    @Json(name = "latitude")
    val latitude: String? = null,
    @Json(name = "location")
    val location: String? = null,
    @Json(name = "longitude")
    val longitude: String? = null,
    @Json(name = "method1")
    val method1: String? = null,
    @Json(name = "method10")
    val method10: String? = null,
    @Json(name = "method2")
    val method2: String? = null,
    @Json(name = "method3")
    val method3: String? = null,
    @Json(name = "method4")
    val method4: String? = null,
    @Json(name = "method5")
    val method5: String? = null,
    @Json(name = "method6")
    val method6: String? = null,
    @Json(name = "method7")
    val method7: String? = null,
    @Json(name = "method8")
    val method8: String? = null,
    @Json(name = "method9")
    val method9: String? = null,
    @Json(name = "neighborhood")
    val neighborhood: String? = null,
    @Json(name = "nta")
    val nta: String? = null,
    @Json(name = "offer_rate1")
    val offerRate1: String? = null,
    @Json(name = "offer_rate2")
    val offerRate2: String? = null,
    @Json(name = "offer_rate3")
    val offerRate3: String? = null,
    @Json(name = "offer_rate4")
    val offerRate4: String? = null,
    @Json(name = "offer_rate5")
    val offerRate5: String? = null,
    @Json(name = "offer_rate6")
    val offerRate6: String? = null,
    @Json(name = "offer_rate7")
    val offerRate7: String? = null,
    @Json(name = "offer_rate8")
    val offerRate8: String? = null,
    @Json(name = "offer_rate9")
    val offerRate9: String? = null,
    @Json(name = "overview_paragraph")
    val overviewParagraph: String? = null,
    @Json(name = "pbat")
    val pbat: String? = null,
    @Json(name = "pct_stu_enough_variety")
    val pctStuEnoughVariety: String? = null,
    @Json(name = "pct_stu_safe")
    val pctStuSafe: String? = null,
    @Json(name = "phone_number")
    val phoneNumber: String? = null,
    @Json(name = "prgdesc1")
    val prgdesc1: String? = null,
    @Json(name = "prgdesc10")
    val prgdesc10: String? = null,
    @Json(name = "prgdesc2")
    val prgdesc2: String? = null,
    @Json(name = "prgdesc3")
    val prgdesc3: String? = null,
    @Json(name = "prgdesc4")
    val prgdesc4: String? = null,
    @Json(name = "prgdesc5")
    val prgdesc5: String? = null,
    @Json(name = "prgdesc6")
    val prgdesc6: String? = null,
    @Json(name = "prgdesc7")
    val prgdesc7: String? = null,
    @Json(name = "prgdesc8")
    val prgdesc8: String? = null,
    @Json(name = "prgdesc9")
    val prgdesc9: String? = null,
    @Json(name = "primary_address_line_1")
    val primaryAddressLine1: String? = null,
    @Json(name = "program1")
    val program1: String? = null,
    @Json(name = "program10")
    val program10: String? = null,
    @Json(name = "program2")
    val program2: String? = null,
    @Json(name = "program3")
    val program3: String? = null,
    @Json(name = "program4")
    val program4: String? = null,
    @Json(name = "program5")
    val program5: String? = null,
    @Json(name = "program6")
    val program6: String? = null,
    @Json(name = "program7")
    val program7: String? = null,
    @Json(name = "program8")
    val program8: String? = null,
    @Json(name = "program9")
    val program9: String? = null,
    @Json(name = "psal_sports_boys")
    val psalSportsBoys: String? = null,
    @Json(name = "psal_sports_coed")
    val psalSportsCoed: String? = null,
    @Json(name = "psal_sports_girls")
    val psalSportsGirls: String? = null,
    @Json(name = "ptech")
    val ptech: String? = null,
    @Json(name = "requirement1_1")
    val requirement11: String? = null,
    @Json(name = "requirement1_2")
    val requirement12: String? = null,
    @Json(name = "requirement1_3")
    val requirement13: String? = null,
    @Json(name = "requirement1_4")
    val requirement14: String? = null,
    @Json(name = "requirement1_5")
    val requirement15: String? = null,
    @Json(name = "requirement1_6")
    val requirement16: String? = null,
    @Json(name = "requirement1_7")
    val requirement17: String? = null,
    @Json(name = "requirement1_8")
    val requirement18: String? = null,
    @Json(name = "requirement2_1")
    val requirement21: String? = null,
    @Json(name = "requirement2_2")
    val requirement22: String? = null,
    @Json(name = "requirement2_3")
    val requirement23: String? = null,
    @Json(name = "requirement2_4")
    val requirement24: String? = null,
    @Json(name = "requirement2_5")
    val requirement25: String? = null,
    @Json(name = "requirement2_6")
    val requirement26: String? = null,
    @Json(name = "requirement2_7")
    val requirement27: String? = null,
    @Json(name = "requirement2_8")
    val requirement28: String? = null,
    @Json(name = "requirement3_1")
    val requirement31: String? = null,
    @Json(name = "requirement3_2")
    val requirement32: String? = null,
    @Json(name = "requirement3_3")
    val requirement33: String? = null,
    @Json(name = "requirement3_4")
    val requirement34: String? = null,
    @Json(name = "requirement3_5")
    val requirement35: String? = null,
    @Json(name = "requirement3_6")
    val requirement36: String? = null,
    @Json(name = "requirement3_7")
    val requirement37: String? = null,
    @Json(name = "requirement3_8")
    val requirement38: String? = null,
    @Json(name = "requirement4_1")
    val requirement41: String? = null,
    @Json(name = "requirement4_2")
    val requirement42: String? = null,
    @Json(name = "requirement4_3")
    val requirement43: String? = null,
    @Json(name = "requirement4_4")
    val requirement44: String? = null,
    @Json(name = "requirement4_5")
    val requirement45: String? = null,
    @Json(name = "requirement4_6")
    val requirement46: String? = null,
    @Json(name = "requirement4_7")
    val requirement47: String? = null,
    @Json(name = "requirement5_1")
    val requirement51: String? = null,
    @Json(name = "requirement5_2")
    val requirement52: String? = null,
    @Json(name = "requirement5_3")
    val requirement53: String? = null,
    @Json(name = "requirement5_4")
    val requirement54: String? = null,
    @Json(name = "requirement5_5")
    val requirement55: String? = null,
    @Json(name = "requirement5_6")
    val requirement56: String? = null,
    @Json(name = "requirement5_7")
    val requirement57: String? = null,
    @Json(name = "requirement6_1")
    val requirement61: String? = null,
    @Json(name = "requirement6_2")
    val requirement62: String? = null,
    @Json(name = "requirement6_3")
    val requirement63: String? = null,
    @Json(name = "requirement6_7")
    val requirement67: String? = null,
    @Json(name = "school_10th_seats")
    val school10thSeats: String? = null,
    @Json(name = "school_accessibility_description")
    val schoolAccessibilityDescription: String? = null,
    @Json(name = "school_email")
    val schoolEmail: String? = null,
    @Json(name = "school_name")
    val schoolName: String? = null,
    @Json(name = "school_sports")
    val schoolSports: String? = null,
    @Json(name = "seats101")
    val seats101: String? = null,
    @Json(name = "seats1010")
    val seats1010: String? = null,
    @Json(name = "seats102")
    val seats102: String? = null,
    @Json(name = "seats103")
    val seats103: String? = null,
    @Json(name = "seats104")
    val seats104: String? = null,
    @Json(name = "seats105")
    val seats105: String? = null,
    @Json(name = "seats106")
    val seats106: String? = null,
    @Json(name = "seats107")
    val seats107: String? = null,
    @Json(name = "seats108")
    val seats108: String? = null,
    @Json(name = "seats109")
    val seats109: String? = null,
    @Json(name = "seats1specialized")
    val seats1specialized: String? = null,
    @Json(name = "seats2specialized")
    val seats2specialized: String? = null,
    @Json(name = "seats3specialized")
    val seats3specialized: String? = null,
    @Json(name = "seats4specialized")
    val seats4specialized: String? = null,
    @Json(name = "seats5specialized")
    val seats5specialized: String? = null,
    @Json(name = "seats6specialized")
    val seats6specialized: String? = null,
    @Json(name = "seats9ge1")
    val seats9ge1: String? = null,
    @Json(name = "seats9ge10")
    val seats9ge10: String? = null,
    @Json(name = "seats9ge2")
    val seats9ge2: String? = null,
    @Json(name = "seats9ge3")
    val seats9ge3: String? = null,
    @Json(name = "seats9ge4")
    val seats9ge4: String? = null,
    @Json(name = "seats9ge5")
    val seats9ge5: String? = null,
    @Json(name = "seats9ge6")
    val seats9ge6: String? = null,
    @Json(name = "seats9ge7")
    val seats9ge7: String? = null,
    @Json(name = "seats9ge8")
    val seats9ge8: String? = null,
    @Json(name = "seats9ge9")
    val seats9ge9: String? = null,
    @Json(name = "seats9swd1")
    val seats9swd1: String? = null,
    @Json(name = "seats9swd10")
    val seats9swd10: String? = null,
    @Json(name = "seats9swd2")
    val seats9swd2: String? = null,
    @Json(name = "seats9swd3")
    val seats9swd3: String? = null,
    @Json(name = "seats9swd4")
    val seats9swd4: String? = null,
    @Json(name = "seats9swd5")
    val seats9swd5: String? = null,
    @Json(name = "seats9swd6")
    val seats9swd6: String? = null,
    @Json(name = "seats9swd7")
    val seats9swd7: String? = null,
    @Json(name = "seats9swd8")
    val seats9swd8: String? = null,
    @Json(name = "seats9swd9")
    val seats9swd9: String? = null,
    @Json(name = "shared_space")
    val sharedSpace: String? = null,
    @Json(name = "specialized")
    val specialized: String? = null,
    @Json(name = "start_time")
    val startTime: String? = null,
    @Json(name = "state_code")
    val stateCode: String? = null,
    @Json(name = "subway")
    val subway: String? = null,
    @Json(name = "total_students")
    val totalStudents: String? = null,
    @Json(name = "transfer")
    val transfer: String? = null,
    @Json(name = "website")
    val website: String? = null,
    @Json(name = "zip")
    val zip: String? = null
)